### ISSUE TITLE
PD Controller frequency

### ISSUE THREAD

**Issue by davidmao829** [zixuan417/smooth-humanoid-locomotion#1]
You mentioned that the simulation frequency is set to 1khz. What is the frequency setting of the actual GR1 deployment? Because of its communication method, the control frequency of GR1 obviously cannot reach 1khz. Looking forward to your reply！

**Comment by zixuan417** [comment]
Simulation frequency is only for the accuracy of simulation, and it's not the same thing as control frequency. Please refer to the deployment code for the control frequency, which is 50Hz.

**Comment by davidmao829** [comment]
Thanks for your answer. In addition, I would like to ask how to determine the key parameters of the delay network used in calculating the torque and the friction force subtracted.

**Comment by zixuan417** [comment]
Hi, these parameters were identified by Fourier. They are closely related to specific actuators.

**Comment by davidmao829** [comment]
Thank you for your reply, it helps me a lot！
