### ISSUE TITLE
request for training grad penalty curve

### ISSUE THREAD

**Issue by EGalahad** [zixuan417/smooth-humanoid-locomotion#2]
Would you kindly release your training grad penalty curves and other reward curves to compare between smoothness rewards / w.o. smoothness rewards / your methods?

It would be beneficial for the community to tune LCP in their codebase to achieve similar behaviour on optimization to achieve good results.

**Comment by zixuan417** [comment]
You can find the training curves in the paper. You should also be able to get similar results by running the codebase with default args.
